language: csharp
solution: "./composer/composer.sln"
install:
  - sudo apt-get install nunit-console
  - nuget restore "./composer/composer.sln"
  - nuget install NUnit.Runners -OutputDirectory testrunner
script: 
  - msbuild ./composer/composer.sln
  - nunit-console --help
  - nunit-console --version
  - nunit-console /home/travis/build/bryce-s/junit_composer/test/bin/Debug/test.dll
  - find . -name "*.nunit*"
