language: csharp
solution: "./composer/composer.sln"
install:
  - nuget restore "./composer/composer.sln"
  - nuget install NUnit.Runners -OutputDirectory testrunner
script: 
  msbuild ./composer/composer.sln
